[build]
  base = "fantabeach"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.close-market]
  schedule = "0 21 * * 4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
